AWSTemplateFormatVersion: "2010-09-09"
Description: HIPAA-Compliant Glue Workflow (Bronze → Silver → Gold)

Parameters:
  ScriptBucket:
    Type: String
    Default: healthcare-data-lake-07091998-csk

Resources:
  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: healthcare-etl-workflow

  BronzeToSilverJob:
    Type: AWS::Glue::Job
    Properties:
      Name: bronze-to-silver
      Role: arn:aws:iam::593026487135:role/HealthcarePipelineRole
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://${ScriptBucket}/scripts/bronze_to_silver.py
        PythonVersion: 3
      GlueVersion: "3.0"
      WorkerType: G.1X
      NumberOfWorkers: 2

  SilverToGoldJob:
    Type: AWS::Glue::Job
    Properties:
      Name: silver-to-gold
      Role: arn:aws:iam::593026487135:role/HealthcarePipelineRole
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://${ScriptBucket}/scripts/silver_to_gold.py
        PythonVersion: 3
      GlueVersion: "3.0"
      WorkerType: G.1X
      NumberOfWorkers: 2

  BronzeTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: bronze-to-silver-trigger
      WorkflowName: !Ref GlueWorkflow
      Type: JOB
      Actions:
        - JobName: !Ref BronzeToSilverJob

  SilverTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: silver-to-gold-trigger
      WorkflowName: !Ref GlueWorkflow
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Ref BronzeToSilverJob
            State: SUCCEEDED
      Actions:
        - JobName: !Ref SilverToGoldJob

Outputs:
  WorkflowName:
    Value: !Ref GlueWorkflow
    Description: Glue Workflow Name
