AWSTemplateFormatVersion: "2010-09-09"
Description: >
  HIPAA-Compliant S3 Data Lake with KMS Encryption, Access Logging, and Restricted Access.

Parameters:
  BucketName:
    Type: String
    Description: Name of the HIPAA-compliant S3 data lake bucket.
  LoggingBucketName:
    Type: String
    Description: Name of the bucket for access logging.
  ETLRoleArn:
    Type: String
    Description: IAM Role ARN for ETL jobs (Glue/SageMaker).

Resources:

  ### 1. KMS Key for Encryption (HIPAA Security Rule)
  DataLakeKMSKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    Properties:
      Description: "KMS key for HIPAA-compliant S3 encryption"
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccountAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  ### 2. Logging Bucket (HIPAA Audit Rule)
  LoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref LoggingBucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ### 3. HIPAA-Compliant Data Lake Bucket
  DataLakeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: access-logs/
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref DataLakeKMSKey
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ### 4. Restrict Bucket Access to ETL Role Only
  DataLakeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataLakeBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowETLRoleAccess
            Effect: Allow
            Principal:
              AWS: !Ref ETLRoleArn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${BucketName}
              - !Sub arn:aws:s3:::${BucketName}/*

Outputs:
  DataLakeBucketName:
    Description: HIPAA S3 Data Lake Bucket
    Value: !Ref DataLakeBucket
  LoggingBucketName:
    Description: Access Logging Bucket
    Value: !Ref LoggingBucket
  KMSKeyArn:
    Description: HIPAA KMS Key ARN
    Value: !Ref DataLakeKMSKey
