name: Deploy HIPAA Infra

on:
  workflow_dispatch:   # Manual trigger from GitHub Actions tab
  push:
    branches:
      - main           # Trigger on main branch push (optional)

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Deploy HIPAA S3 Stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/hipaa_s3_bucket.yml \
          --stack-name hipaa-s3-datalake \
          --parameter-overrides \
            BucketName=healthcare-data-lake \
            LoggingBucketName=healthcare-logs \
            ETLRoleArn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/HealthcarePipelineRole \
          --capabilities CAPABILITY_NAMED_IAM
