name: Ingest CMS Medicare Claims (Bronze)

on:
  workflow_dispatch:   # Manual trigger

jobs:
  ingest-cms-claims:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 4: Install Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pandas requests

      # Step 5: Run Ingestion Script
      - name: Run CMS Claims Ingestion
        run: python etl/ingest_cms_claims.py
